packages:
  gl_s10: !include configs/gl_s10.yaml
  static_ip: !include configs/static-ip-eth.yaml
  landing_iam_t1: !include
    file: configs/inkbird_iam_t1.yaml
    vars:
      mac_address: !secret iam_t1_landing_mac
      sub_device_area_id: landing_area
      sub_device_friendly_name: Landing IAM-T1
      sub_device_name: iam_t1_landing
  main_bedroom_iam_t1: !include
    file: configs/inkbird_iam_t1.yaml
    vars:
      mac_address: !secret iam_t1_main_bedroom_mac
      sub_device_area_id: main_bedroom_area
      sub_device_friendly_name: Main Bedroom IAM-T1
      sub_device_name: iam_t1_main_bedroom
  office_iam_t1: !include
    file: configs/inkbird_iam_t1.yaml
    vars:
      mac_address: !secret iam_t1_office_mac
      sub_device_area_id: office_area
      sub_device_friendly_name: Office IAM-T1
      sub_device_name: iam_t1_office

substitutions:
  friendly_name: CO2 Relay
  ip_address: 10.1.1.226
  name: co2-relay

esphome:
  areas:
    - id: landing_area
      name: Landing
    - id: main_bedroom_area
      name: Main Bedroom
    - id: office_area
      name: Office
