substitutions:
  fallback_name: $name Fallback

# Setup WiFi connection and fallback AP
wifi:
  ap:
    password: !secret fallback_psk
    ssid: $fallback_name
  min_auth_mode: WPA2
  password: !secret psk
  ssid: !secret ssid

# Enable fallback captive portal when WiFi fails
captive_portal:
